// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/blogs" | "/admin/donations" | "/admin/partners" | "/admin/projects" | "/admin/reports" | "/admin/settings" | "/admin/stories" | "/admin/team" | "/admin/users" | "/api/login" | "/blogs" | "/blogs/[slug]" | "/contact" | "/donate" | "/donate/verify" | "/get-involved" | "/login" | "/programs" | "/programs/climate-justice" | "/programs/education" | "/programs/environmental-conservation" | "/programs/srhr" | "/projects" | "/volunteer"
type AppRouteHandlerRoutes = "/api/analytics/stats" | "/api/analytics/track" | "/api/blogs" | "/api/blogs/[id]" | "/api/contact" | "/api/debug" | "/api/donations/card" | "/api/donations/checkout" | "/api/donations/mobile-money" | "/api/donations/verify/[referenceId]" | "/api/nextauth/[...nextauth]" | "/api/partners" | "/api/partners/[id]" | "/api/partners/list" | "/api/projects" | "/api/projects/[id]" | "/api/stats" | "/api/team" | "/api/team/[id]" | "/api/upload/cloudinary" | "/api/volunteers" | "/api/webhooks/paychangu"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/blogs": {}
  "/admin/donations": {}
  "/admin/partners": {}
  "/admin/projects": {}
  "/admin/reports": {}
  "/admin/settings": {}
  "/admin/stories": {}
  "/admin/team": {}
  "/admin/users": {}
  "/api/analytics/stats": {}
  "/api/analytics/track": {}
  "/api/blogs": {}
  "/api/blogs/[id]": { "id": string; }
  "/api/contact": {}
  "/api/debug": {}
  "/api/donations/card": {}
  "/api/donations/checkout": {}
  "/api/donations/mobile-money": {}
  "/api/donations/verify/[referenceId]": { "referenceId": string; }
  "/api/login": {}
  "/api/nextauth/[...nextauth]": { "nextauth": string[]; }
  "/api/partners": {}
  "/api/partners/[id]": { "id": string; }
  "/api/partners/list": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/stats": {}
  "/api/team": {}
  "/api/team/[id]": { "id": string; }
  "/api/upload/cloudinary": {}
  "/api/volunteers": {}
  "/api/webhooks/paychangu": {}
  "/blogs": {}
  "/blogs/[slug]": { "slug": string; }
  "/contact": {}
  "/donate": {}
  "/donate/verify": {}
  "/get-involved": {}
  "/login": {}
  "/programs": {}
  "/programs/climate-justice": {}
  "/programs/education": {}
  "/programs/environmental-conservation": {}
  "/programs/srhr": {}
  "/projects": {}
  "/volunteer": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
